// Task calculation utilities based on task_count_by_duration.js reference
// This ensures consistent task count calculations across the application

/**
 * Calculate the minimum number of tasks required for a given timeline
 * @param {number} months - Timeline in months (1-24)
 * @returns {object} - Object containing totalDays, minTasks, and other metrics
 */
export const calculateTaskRequirements = (months) => {
    // Ensure months is a valid number between 1-24
    const validMonths = Math.max(1, Math.min(24, Number(months) || 1));

    // Formula from task_count_by_duration.js
    const totalDays = Math.max(30, Math.round(validMonths * 30));
    const minTasks = Math.max(30, Math.round(totalDays * 0.8));

    // Additional metrics for reference
    const tasksPerDay = minTasks / totalDays;
    const tasksPerWeek = minTasks / (totalDays / 7);

    // Calculate target and recommended task counts
    const targetTasks = minTasks + 10; // Add buffer for better success rate
    const recommendedTasks = Math.round(minTasks * 1.2); // 20% more for comprehensive coverage

    return {
        months: validMonths,
        totalDays,
        minTasks,
        targetTasks,
        recommendedTasks,
        tasksPerDay: Math.round(tasksPerDay * 10) / 10, // Round to 1 decimal
        tasksPerWeek: Math.round(tasksPerWeek * 10) / 10,
        intensity: getWorkloadIntensity(tasksPerDay)
    };
};

/**
 * Get workload intensity level based on tasks per day
 * @param {number} tasksPerDay - Average tasks per day
 * @returns {string} - Intensity level
 */
const getWorkloadIntensity = (tasksPerDay) => {
    if (tasksPerDay >= 1.0) return "Intensive";
    if (tasksPerDay >= 0.8) return "Moderate";
    if (tasksPerDay >= 0.6) return "Light";
    return "Very Light";
};

/**
 * Validate if the generated task count meets the minimum requirements
 * @param {number} generatedTaskCount - Number of tasks generated by AI
 * @param {number} months - Timeline in months
 * @returns {object} - Validation result with details
 */
export const validateTaskCount = (generatedTaskCount, months) => {
    const requirements = calculateTaskRequirements(months);
    const isValid = generatedTaskCount >= requirements.minTasks;

    return {
        isValid,
        generatedCount: generatedTaskCount,
        requiredCount: requirements.minTasks,
        shortfall: isValid ? 0 : requirements.minTasks - generatedTaskCount,
        requirements
    };
};

/**
 * Get supported duration options with their task requirements
 * @returns {array} - Array of duration options with task counts
 */
export const getSupportedDurations = () => {
    const durations = [1, 2, 3, 4, 6, 12];

    return durations.map(months => ({
        months,
        label: `${months} Month${months > 1 ? 's' : ''}`,
        ...calculateTaskRequirements(months)
    }));
};

/**
 * Print task count breakdown for all supported durations (for debugging)
 */
export const printTaskCountBreakdown = () => {
    console.log("=== MINIMUM TASK COUNTS BY DURATION ===");
    console.log("\n📊 TASK COUNT BREAKDOWN:");
    console.log("Duration | Total Days | Min Tasks | Tasks/Day | Tasks/Week");
    console.log("---------|------------|-----------|-----------|------------");

    const durations = getSupportedDurations();
    durations.forEach(({ label, totalDays, minTasks, tasksPerDay, tasksPerWeek }) => {
        console.log(`${label.padEnd(8)} | ${totalDays.toString().padEnd(10)} | ${minTasks.toString().padEnd(9)} | ${tasksPerDay.toString().padEnd(9)} | ${tasksPerWeek}`);
    });

    console.log("\n⚡ WORKLOAD ANALYSIS:");
    durations.forEach(({ label, minTasks, intensity }) => {
        console.log(`${label}: ${minTasks} tasks = ${intensity}`);
    });

    console.log("\n✅ SYSTEM VALIDATION:");
    console.log("• AI will retry up to 3 times if insufficient tasks generated");
    console.log("• Each duration gets appropriate task count automatically");
    console.log("• Phase distribution ensures comprehensive coverage");
    console.log("• Time estimation matches user's daily availability");
};